# \u914D\u7F6E\u7AEF\u53E3
server:
  port: 8081
spring:
  # \u914D\u7F6E\u6570\u636E\u6E90
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mp_student?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
# mybatis-plus\u76F8\u5173\u914D\u7F6E
mybatis-plus:
  # xml\u626B\u63CF\uFF0C\u591A\u4E2A\u76EE\u5F55\u7528\u9017\u53F7\u6216\u8005\u5206\u53F7\u5206\u9694\uFF08\u544A\u8BC9 Mapper \u6240\u5BF9\u5E94\u7684 XML \u6587\u4EF6\u4F4D\u7F6E\uFF09
  mapper-locations: classpath:mapper/*.xml
  # \u4EE5\u4E0B\u914D\u7F6E\u5747\u6709\u9ED8\u8BA4\u503C,\u53EF\u4EE5\u4E0D\u8BBE\u7F6E
  global-config:
    db-config:
      #\u4E3B\u952E\u7C7B\u578B AUTO:"\u6570\u636E\u5E93ID\u81EA\u589E" INPUT:"\u7528\u6237\u8F93\u5165ID",ID_WORKER:"\u5168\u5C40\u552F\u4E00ID (\u6570\u5B57\u7C7B\u578B\u552F\u4E00ID)", UUID:"\u5168\u5C40\u552F\u4E00ID UUID";
      id-type: auto
      #\u5B57\u6BB5\u7B56\u7565 IGNORED:"\u5FFD\u7565\u5224\u65AD"  NOT_NULL:"\u975E NULL \u5224\u65AD")  NOT_EMPTY:"\u975E\u7A7A\u5224\u65AD"
      field-strategy: NOT_EMPTY
      #\u6570\u636E\u5E93\u7C7B\u578B
      db-type: MYSQL
  configuration:
    # 开启驼峰功能
    map-underscore-to-camel-case: true
    # 对象中null属性也进行传值
    call-setters-on-nulls: true
    # \u8FD9\u4E2A\u914D\u7F6E\u4F1A\u5C06\u6267\u884C\u7684sql\u6253\u5370\u51FA\u6765\uFF0C\u5728\u5F00\u53D1\u6216\u6D4B\u8BD5\u7684\u65F6\u5019\u53EF\u4EE5\u7528
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
